language: node_js
node_js:
  - '10'

services:
  - docker

before_install:
  - npm i omg

script:
  - npx omg build
  - |
    control="$(curl https://httpbin.org/html)"
    output="$(npx omg run --raw scrape -a url="https://httpbin.org/html" | jq -c .)"
    if [ "$output" != '{"html":"$control"}' ] ; then echo "$output"; exit 1; fi
